name: CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.target == 'i686-pc-windows-gnu' && format('{0}-i686-pc-windows-gnu', matrix.channel) || matrix.channel }}
          target: ${{ matrix.target }}
          override: true
          components: rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - env:
          CHANNEL: ${{ matrix.channel }}
          CROSS: ${{ !startsWith(matrix.target, 'x86_64') && contains(matrix.target, 'linux') && '1' || '0' }}
          TARGET: ${{ matrix.target }}
          OS: ${{ matrix.os }}
          PROJECT_DIR: ${{ github.workspace }}
        run: sh .github/workflows/ci.sh

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            channel: stable
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            channel: nightly
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
            channel: stable
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
            channel: nightly
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            channel: stable
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
            channel: nightly
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            channel: stable
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
            channel: nightly
          - target: riscv64gc-unknown-linux-gnu
            os: ubuntu-latest
            channel: stable
          - target: riscv64gc-unknown-linux-gnu
            os: ubuntu-latest
            channel: nightly
#          - target: mips64-unknown-linux-muslabi64
#            os: ubuntu-latest
#            channel: stable
#          - target: mips64-unknown-linux-muslabi64
#            os: ubuntu-latest
#            channel: nightly
#          - target: loongarch64-unknown-linux-gnu
#            os: ubuntu-latest
#            channel: stable
#          - target: loongarch64-unknown-linux-gnu
#            os: ubuntu-latest
#            channel: nightly
#          - target: s390x-unknown-linux-gnu
#            os: ubuntu-latest
#            channel: stable
#          - target: s390x-unknown-linux-gnu
#            os: ubuntu-latest
#            channel: nightly

          - target: x86_64-apple-darwin
            os: macos-latest
            channel: stable
          - target: x86_64-apple-darwin
            os: macos-latest
            channel: nightly
          - target: aarch64-apple-darwin
            os: macos-14
            channel: stable
          - target: aarch64-apple-darwin
            os: macos-14
            channel: nightly

          - target: x86_64-pc-windows-gnu
            os: windows-latest
            channel: nightly
          - target: i686-pc-windows-gnu
            os: windows-latest
            channel: nightly
#          - target: x86_64-pc-windows-msvc
#            os: windows-latest
#            channel: nightly
#          - target: i686-pc-windows-msvc
#            os: windows-latest
#            channel: nightly
